apiVersion: apps/v1
kind: ReplicationSet
metadata:
  name: myonlineapp-rc
spec:
   replicas: 3
   selector: 
     matchExpressions:
       - { key: app, operator: In, values: {“myonlineapp”}}
   template:                                     
     metadata:
       labels:
          app: myonlineapp
     spec:
        containers:
        - name: myonlineapp-container
          image: nbktechnosys/myjavaimage11nov22:1
          ports:
          - containerPort: 8080 

