apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myonlineapp-rc
spec:
   replicas: 3
   selector: 
     matchExpressions:
       - { key: app, operator: In, values: ["myonlineapp","webserver"] }
   template:                                     
     metadata:
       name: nginx-my  
       labels:
          app: webserver
     spec:
        containers:
        - name: myonlineapp-container
          image: nbktechnosys/myjavaimage11nov22:1
          ports:
          - containerPort: 8080 

