apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-deploy1
  labels:
     app: myvertexapp1
spec:
  replicas: 4
  selector:
      matchLabels:
        app: myvertexapp1
  template:
     metadata:
       labels:
           app: myvertexapp1
     spec:
       containers:
       - name: myjavaapp-container
         image:  nbktechnosys/myjavaimages2dec22:1
         ports:
         - containerPort: 8080