apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
spec:
  imagePullSecrets:
    - name: docker-hub  
  containers:
    - name: demo
      image: nbktechnosys/myjavaapp4april23:1
      ports: 
        - containerPort: 8080